version: 2

models:
  - name: dim_vendors
    description: "This table contains vendor information."
    columns:
      - name: vendor_id
        description: "The unique identifier for each vendor."
      - name: vendor_name
        description: "The name of the vendor."
        tests:
          - not_null
      - name: vendor_address
        description: "The address of the vendor."
      - name: vendor_phone
        description: "The contact phone number for the vendor."
      - name: created_at
        description: "The timestamp when the vendor record was created."
      - name: updated_at
        description: "The timestamo when the vendor record was last updated."