# Zoomcamp template: pipeline.yml
# Key docs:
# - Pipeline files: https://getbruin.com/docs/bruin/getting-started/pipeline
# - Variables (JSON Schema): https://getbruin.com/docs/bruin/getting-started/pipeline-variables
# - Run command: https://getbruin.com/docs/bruin/commands/run

# Pipeline name (shows up in logs + `BRUIN_PIPELINE` for Python assets).
name: nyc-taxi

# Schedule: "daily", "hourly", "weekly", "monthly", or a cron string.
schedule: "monthly"

# Earliest date this pipeline should consider for full refresh backfills.
start_date: "2022-01-01"

# Default connections so assets can omit explicit `connection: ...`.
# Docs (connections): https://getbruin.com/docs/bruin/commands/connections
default_connections:
  duckdb: duckdb-default

# Pipeline variables using JSON Schema and defaults.
# - Variables must have a `default` so assets can render without `--var`.
# - In SQL/YAML assets: reference as `{{ var.my_variable }}`.
# - In Python assets: read JSON from env var `BRUIN_VARS`.
variables:
  # `taxi_types` controls which taxi types are ingested each run.
  taxi_types:
    type: array
    items:
      type: string
    default: ["yellow"]  # e.g. ["yellow", "green"]
